/**
 * Ink boxes for the jamo, in em, y-up with the baseline at 0. Generated by
 * scripts/build-loader.mjs — do not edit by hand; re-run the script.
 *
 * The loader fits each jamo into a cell of its syllable block, and a cell fit
 * needs ink bounds rather than layout bounds.
 */

export interface InkBox {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

export const JAMO_INK: Record<string, InkBox> = {
  "ㅂ": { x1: 0.165, y1: 0.125, x2: 0.707, y2: 0.5928 },
  "ㅏ": { x1: 0.3682, y1: -0.0791, x2: 0.6494, y2: 0.7725 },
  "ㄱ": { x1: 0.1602, y1: 0.126, x2: 0.7041, y2: 0.5781 },
  "ㅅ": { x1: 0.1279, y1: 0.1162, x2: 0.7461, y2: 0.5986 },
  "ㅇ": { x1: 0.1592, y1: 0.1191, x2: 0.7061, y2: 0.5967 },
  "ㅎ": { x1: 0.1465, y1: 0.083, x2: 0.7275, y2: 0.6426 },
  "ㅕ": { x1: 0.2754, y1: -0.0771, x2: 0.5605, y2: 0.7744 },
  "ㄴ": { x1: 0.166, y1: 0.1328, x2: 0.7207, y2: 0.5781 },
};

/**
 * The composed syllables, measured the same way.
 *
 * The animation crossfades a block's assembled parts into the syllable itself,
 * and the two have to occupy the same box for that to read as tightening
 * rather than as one image ghosting over another.
 */
export const SYLLABLE_INK: Record<string, InkBox> = {
  "박": { x1: 0.0723, y1: -0.0791, x2: 0.8447, y2: 0.7891 },
  "상": { x1: 0.0322, y1: -0.0771, x2: 0.8447, y2: 0.7891 },
  "현": { x1: 0.0361, y1: -0.0605, x2: 0.7744, y2: 0.7891 },
};
