/**
 * Glyph metadata for the Hangul hero. Generated by scripts/bake-glyphs.mjs —
 * do not edit by hand; re-run the script instead.
 *
 * Source: Noto Sans KR Bold (SIL Open Font License 1.1)
 * https://fonts.gstatic.com/s/notosanskr/v39/PbyxFmXiEBPT4ITbgNA5Cgms3VYcOA-vvnIzzg01eLQ.ttf
 *
 * The outlines themselves are not here. They are rasterised into signed
 * distance fields in glyphs.sdf.bin, one tile per glyph, and this
 * module only says where each glyph's tile is and how big its ink was. All
 * measurements are in ems, y-up, baseline at 0.
 */

export interface AtlasMeta {
  /** Filename of the distance-field atlas, alongside this module. */
  file: string;
  /** Edge length of one tile, in texels. */
  tile: number;
  cols: number;
  rows: number;
  /** Fraction of a tile the glyph's bounding box was stretched to fill. */
  ink: number;
  /** Tile-widths of distance the encoded byte range spans, ±. */
  spread: number;
}

export interface BakedGlyph {
  advanceWidth: number;
  /** [x1, y1, x2, y2] of the ink, in ems. */
  bbox: [number, number, number, number];
  /** Index of this glyph's tile in the atlas, in row-major order. */
  tile: number;
}

export const ATLAS: AtlasMeta = {
  file: "glyphs.sdf.bin",
  tile: 128,
  cols: 4,
  rows: 4,
  ink: 0.66,
  spread: 0.25,
};

export const GLYPHS: Record<string, BakedGlyph> = {
  "ㅂ": { advanceWidth: 0.92, bbox: [0.169, 0.129, 0.754, 0.641], tile: 0 },
  "ㅏ": { advanceWidth: 0.92, bbox: [0.364, -0.087, 0.687, 0.83], tile: 1 },
  "ㄱ": { advanceWidth: 0.92, bbox: [0.167, 0.13, 0.753, 0.629], tile: 2 },
  "ㅅ": { advanceWidth: 0.92, bbox: [0.125, 0.114, 0.798, 0.645], tile: 3 },
  "ㅇ": { advanceWidth: 0.92, bbox: [0.166, 0.119, 0.756, 0.644], tile: 4 },
  "ㅎ": { advanceWidth: 0.92, bbox: [0.157, 0.08, 0.768, 0.711], tile: 5 },
  "ㅕ": { advanceWidth: 0.92, bbox: [0.29, -0.088, 0.621, 0.829], tile: 6 },
  "ㄴ": { advanceWidth: 0.92, bbox: [0.167, 0.145, 0.763, 0.629], tile: 7 },
  "S": { advanceWidth: 0.624, bbox: [0.042, -0.014, 0.584, 0.754], tile: 8 },
  "e": { advanceWidth: 0.581, bbox: [0.044, -0.014, 0.539, 0.574], tile: 9 },
  "a": { advanceWidth: 0.591, bbox: [0.051, -0.014, 0.52, 0.574], tile: 10 },
  "n": { advanceWidth: 0.641, bbox: [0.079, 0, 0.568, 0.574], tile: 11 },
  "P": { advanceWidth: 0.667, bbox: [0.091, 0, 0.624, 0.741], tile: 12 },
  "r": { advanceWidth: 0.437, bbox: [0.079, 0, 0.437, 0.574], tile: 13 },
  "k": { advanceWidth: 0.604, bbox: [0.079, 0, 0.598, 0.798], tile: 14 },
};
