#!/usr/bin/env node
/**
 * Bakes the loader's glyphs to SVG path data.
 *
 *   npm run build:loader
 *
 * Outlines only — no triangulation, no extrusion, no mesh. The loader draws
 * 박상현 and "Sean Park" as filled SVG paths, which is why it has no font to
 * download, no WebGL context to create, and none of the tessellation faults
 * that come with turning a letterform into geometry.
 *
 * Output is a few KB of path strings in src/loader/glyphs.ts, committed.
 */
import fs from "node:fs";
import path from "node:path";

import opentype from "opentype.js";

/**
 * Two weights of one family.
 *
 * The contrast is the idea, not a fallback for lacking a second typeface. The
 * Korean name is set thin and widely tracked — quiet, editorial, the name on
 * the family register. The English one is set black and tight. Same letterforms
 * underneath, so the swap cannot read as a change of typeface; only of voice.
 *
 * Pinned as a devDependency. Neither file is ever shipped — what ships is the
 * path data below.
 */
const FONTS = {
  hangul: "node_modules/pretendard/dist/public/static/Pretendard-Light.otf",
  latin: "node_modules/pretendard/dist/public/static/Pretendard-Black.otf",
};
const OUT = path.join("src", "loader", "glyphs.ts");

/** Path data is emitted at this size, so the numbers stay readable. */
const SIZE = 100;

/**
 * Letterspacing, as a fraction of the size.
 *
 * Wide on the Hangul: three syllables set thin need air or they read as a
 * word rather than as three separate blocks. Slightly negative on the Latin,
 * because a black weight at display size sets too loose at its native
 * sidebearings.
 */
const TRACKING = { hangul: 0.14, latin: -0.012 };

function run(font, text, tracking) {
  const glyphs = [];
  let pen = 0;

  for (const char of text) {
    const glyph = font.charToGlyph(char);
    if (!glyph || glyph.index === 0) throw new Error(`${char} is not in the font`);

    if (char === " ") {
      pen += (glyph.advanceWidth / font.unitsPerEm) * SIZE;
      continue;
    }

    // getPath returns y-down coordinates, which is what SVG wants — so the
    // path data goes straight into a <path d> with no flip.
    const outline = glyph.getPath(pen, 0, SIZE);
    glyphs.push({ char, d: outline.toPathData(2) });

    pen += (glyph.advanceWidth / font.unitsPerEm) * SIZE + tracking * SIZE;
  }

  return { glyphs, width: pen - tracking * SIZE };
}

function main() {
  const load = (file) => opentype.parse(fs.readFileSync(file).buffer);

  const hangul = run(load(FONTS.hangul), "박상현", TRACKING.hangul);
  const latin = run(load(FONTS.latin), "SEAN PARK", TRACKING.latin);

  // A viewBox tall enough for both, with the baseline at y = 0. Ascenders run
  // negative in this space and descenders positive, which is why the box
  // starts above zero.
  const top = -SIZE * 0.9;
  const height = SIZE * 1.15;

  const serialise = (run_) =>
    run_.glyphs
      .map((g) => `  { char: ${JSON.stringify(g.char)}, d: ${JSON.stringify(g.d)} },`)
      .join("\n");

  const module = `/**
 * Glyph outlines for the loader. Generated by scripts/build-loader.mjs — do
 * not edit by hand; re-run the script.
 *
 * Source: Pretendard (SIL Open Font License 1.1) — Light for the Hangul,
 * Black for the Latin.
 *
 * SVG path data, y-down, baseline on y = 0, drawn at ${SIZE} units per em.
 * Each glyph is already positioned along its run, so a run renders as a list
 * of <path> elements in one coordinate space.
 */

export interface Glyph {
  char: string;
  d: string;
}

export interface Run {
  glyphs: Glyph[];
  width: number;
}

/** The viewBox both runs are drawn in. */
export const VIEW = { top: ${top}, height: ${height} };

export const HANGUL: Run = {
  width: ${hangul.width.toFixed(2)},
  glyphs: [
${serialise(hangul)}
  ],
};

export const LATIN: Run = {
  width: ${latin.width.toFixed(2)},
  glyphs: [
${serialise(latin)}
  ],
};
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, module);

  const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
  process.stderr.write(
    `wrote ${OUT} — ${hangul.glyphs.length} + ${latin.glyphs.length} glyphs, ${kb} KB\n`,
  );
}

main();
