#!/usr/bin/env node
/**
 * Subsets Pretendard Variable down to the glyphs the loader draws.
 *
 *   npm run build:loader
 *
 * The whole point is the weight axis. Pretendard Variable carries wght 45–930,
 * and the loader animates along it — the name gains weight as the page loads —
 * so the subset has to keep `fvar` and `gvar` rather than flattening to a
 * static instance.
 *
 * Eleven glyphs and a space come to under 3 KB as woff2, which is less than
 * the SVG path data this replaced, and it buys real selectable text instead of
 * a wall of <path> elements.
 *
 * Needs fonttools and brotli:  python3 -m pip install fonttools brotli
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

import opentype from "opentype.js";

const SOURCE = "node_modules/pretendard/dist/public/variable/PretendardVariable.ttf";
/**
 * Deliberately not in public/fonts/.
 *
 * scripts/fetch-fonts.py rebuilds that directory from scratch and unlinks every
 * *.woff2 it finds, so a font living there that it does not know about is one
 * `python3 scripts/fetch-fonts.py` away from vanishing — and the loader would
 * quietly fall back to a system face with the weight axis animating nothing.
 */
const OUT = path.join("public", "loader", "pretendard-var.woff2");

/**
 * Every character the loader can render.
 *
 * The nine jamo of 박상현 as well as the composed syllables: the animation
 * assembles each block from its parts before showing the block itself, which
 * is how Korean actually works and is the whole idea of the piece.
 */
const JAMO = "ㅂㅏㄱㅅㅇㅎㅕㄴ";
const TEXT = `박상현SEANPRK ${JAMO}`;

function main() {
  if (!fs.existsSync(SOURCE)) {
    throw new Error(`${SOURCE} is missing — run npm install`);
  }

  fs.mkdirSync(path.dirname(OUT), { recursive: true });

  execFileSync(
    "python3",
    [
      "-m",
      "fontTools.subset",
      SOURCE,
      `--text=${TEXT}`,
      "--flavor=woff2",
      // The loader sets plain spans; none of the layout features are reachable,
      // and dropping them takes the file down by more than half.
      "--layout-features=",
      "--no-hinting",
      "--desubroutinize",
      `--output-file=${OUT}`,
    ],
    { stdio: ["ignore", "ignore", "inherit"] },
  );

  writeMetrics();

  const bytes = fs.statSync(OUT).size;
  process.stderr.write(
    `wrote ${OUT} — ${[...new Set(TEXT.replace(" ", ""))].length} glyphs, ${(bytes / 1024).toFixed(1)} KB\n`,
  );
}

/**
 * Emits the ink box of each jamo, in em.
 *
 * The loader fits every jamo into a cell of its syllable block, which needs to
 * know how much ink each one actually has — and a DOM measurement gives the
 * layout box, which is the em square plus sidebearings, not the ink. Measuring
 * here is exact, costs nothing at runtime, and removes a font-load race from
 * mount.
 *
 * Taken at weight 300, near where the jamo are drawn. The axis moves the ink
 * box slightly; at the scale these are rendered the difference is under a
 * pixel and not worth carrying a table of boxes per weight.
 */
function writeMetrics() {
  const font = opentype.parse(fs.readFileSync(SOURCE).buffer);
  font.variation.set({ wght: 300 });

  const em = font.unitsPerEm;
  const round = (n) => +(n / em).toFixed(4);

  const inkOf = (char) => {
    const box = font.charToGlyph(char).getBoundingBox();
    return `{ x1: ${round(box.x1)}, y1: ${round(box.y1)}, x2: ${round(box.x2)}, y2: ${round(box.y2)} }`;
  };

  const syllables = [..."박상현"]
    .map((char) => `  ${JSON.stringify(char)}: ${inkOf(char)},`)
    .join("\n");

  const entries = [...JAMO]
    .map((char) => {
      const box = font.charToGlyph(char).getBoundingBox();
      return (
        `  ${JSON.stringify(char)}: ` +
        `{ x1: ${round(box.x1)}, y1: ${round(box.y1)}, x2: ${round(box.x2)}, y2: ${round(box.y2)} },`
      );
    })
    .join("\n");

  const module = `/**
 * Ink boxes for the jamo, in em, y-up with the baseline at 0. Generated by
 * scripts/build-loader.mjs — do not edit by hand; re-run the script.
 *
 * The loader fits each jamo into a cell of its syllable block, and a cell fit
 * needs ink bounds rather than layout bounds.
 */

export interface InkBox {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

export const JAMO_INK: Record<string, InkBox> = {
${entries}
};

/**
 * The composed syllables, measured the same way.
 *
 * The animation crossfades a block's assembled parts into the syllable itself,
 * and the two have to occupy the same box for that to read as tightening
 * rather than as one image ghosting over another.
 */
export const SYLLABLE_INK: Record<string, InkBox> = {
${syllables}
};
`;

  fs.writeFileSync(path.join("src", "loader", "metrics.ts"), module);
}

main();
