#!/usr/bin/env python3
"""Fetch latin-subset woff2 webfonts from Google Fonts into public/fonts/.

Rewrites the @font-face rules to local URLs and writes them to src/fonts.css.
Run from the repository root when the font set changes; the output is committed.
"""
import re
import subprocess
import pathlib

UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/120 Safari/537.36"
OUT = pathlib.Path("public/fonts")

FAMILIES = [
    "Inter:wght@400;500;600",
    "Inter+Tight:wght@400;500;600",
    "Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,600;1,6..72,400",
    "IBM+Plex+Sans:wght@400;600",
    "IBM+Plex+Mono:wght@400;500",
]


def get(url: str, binary: bool = False):
    result = subprocess.run(
        ["curl", "-sS", "--max-time", "40", "-A", UA, url],
        capture_output=True,
        check=True,
    )
    return result.stdout if binary else result.stdout.decode()


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    css = get(
        "https://fonts.googleapis.com/css2?"
        + "&".join(f"family={f}" for f in FAMILIES)
        + "&display=swap"
    )

    # Each @font-face block is preceded by a /* subset */ comment; keep latin only.
    blocks = re.split(r"/\*\s*([\w-]+)\s*\*/", css)
    rules: list[str] = []
    seen: set[str] = set()

    for subset, body in zip(blocks[1::2], blocks[2::2]):
        if subset != "latin":
            continue

        def localise(match: re.Match) -> str:
            url = match.group(1)
            name = url.rsplit("/", 1)[-1]
            if name not in seen:
                (OUT / name).write_bytes(get(url, binary=True))
                seen.add(name)
            return f"url(/fonts/{name})"

        rules.append(
            re.sub(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", localise, body).strip()
        )

    header = (
        "/* Self-hosted latin-subset webfonts (SIL Open Font License 1.1).\n"
        "   Regenerated by scripts/fetch-fonts.py — do not edit by hand. */\n\n"
    )
    pathlib.Path("src/fonts.css").write_text(header + "\n\n".join(rules) + "\n")
    total = sum(f.stat().st_size for f in OUT.iterdir()) // 1024
    print(f"{len(seen)} files, {total} KB")


if __name__ == "__main__":
    main()
