#!/usr/bin/env python3
"""Fetch the site's webfonts into public/fonts/ and write src/fonts.css.

Three faces, three jobs:

  Schibsted Grotesk  display and text. Chosen because it is a metric twin of
                     Pretendard — cap 703 vs 707, x-height 527 vs 530, an
                     identical 0.750 x/cap ratio — so Korean and Latin sit on
                     one baseline with no optical fudging.
  IBM Plex Mono      labels, field names, metrics. Cap 698, within 1.3% of
                     Pretendard, so mono labels align to Korean too.
  Pretendard         Korean. Subset to the glyphs the site actually sets,
                     which takes it from 1.5 MB to a couple of kilobytes.

Run from the repository root when the font set changes; the output is
committed, so the build itself needs neither Python nor network.

Requires: pip install fonttools brotli
"""
import pathlib
import re
import subprocess

UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/120 Safari/537.36"
OUT = pathlib.Path("public/fonts")

FAMILIES = [
    "Schibsted+Grotesk:wght@400..900",
    "IBM+Plex+Mono:wght@400;500",
]

PRETENDARD = (
    "https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9"
    "/packages/pretendard/dist/public/static/Pretendard-{weight}.otf"
)

# Every Korean character the site sets, including the decomposed jamo of the
# name motif. Anything added to the copy must be added here or it will fall
# back to a system face and break the baseline match.
KOREAN = (
    "박상현"  # the name, composed
    "ㅂㅏㄱㅅㅏㅇㅎㅕㄴ"  # the name, decomposed into compatibility jamo
    "한국장학재단"  # Korea Student Aid Foundation
    "마인드로직"  # Mindlogic
)


def get(url: str, binary: bool = False):
    result = subprocess.run(
        ["curl", "-sSL", "--max-time", "60", "-A", UA, url],
        capture_output=True,
        check=True,
    )
    return result.stdout if binary else result.stdout.decode()


def google_fonts() -> list[str]:
    """Download the latin subsets and return rewritten @font-face rules."""
    css = get(
        "https://fonts.googleapis.com/css2?"
        + "&".join(f"family={f}" for f in FAMILIES)
        + "&display=swap"
    )

    # Each @font-face block is preceded by a /* subset */ comment; keep latin only.
    blocks = re.split(r"/\*\s*([\w-]+)\s*\*/", css)
    rules: list[str] = []
    seen: set[str] = set()

    for subset, body in zip(blocks[1::2], blocks[2::2]):
        if subset != "latin":
            continue

        def localise(match: re.Match) -> str:
            url = match.group(1)
            name = url.rsplit("/", 1)[-1]
            if name not in seen:
                (OUT / name).write_bytes(get(url, binary=True))
                seen.add(name)
            return f"url(/fonts/{name})"

        rules.append(
            re.sub(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", localise, body).strip()
        )

    return rules


def pretendard() -> list[str]:
    """Subset Pretendard to KOREAN and return its @font-face rules."""
    rules = []

    for weight, css_weight in (("Regular", 400), ("SemiBold", 600)):
        source = OUT / f".Pretendard-{weight}.otf"
        source.write_bytes(get(PRETENDARD.format(weight=weight), binary=True))
        name = f"pretendard-{css_weight}-subset.woff2"

        subprocess.run(
            [
                "pyftsubset",
                str(source),
                f"--text={KOREAN}",
                "--flavor=woff2",
                f"--output-file={OUT / name}",
                "--layout-features=*",
                "--no-hinting",
                "--desubroutinize",
            ],
            check=True,
        )
        source.unlink()

        rules.append(
            "@font-face {\n"
            "  font-family: 'Pretendard';\n"
            "  font-style: normal;\n"
            f"  font-weight: {css_weight};\n"
            "  font-display: swap;\n"
            f"  src: url(/fonts/{name}) format('woff2');\n"
            "}"
        )

    return rules


def main() -> None:
    # Rebuild from scratch so a dropped family cannot leave orphaned files behind.
    if OUT.exists():
        for stale in OUT.iterdir():
            stale.unlink()
    OUT.mkdir(parents=True, exist_ok=True)

    rules = google_fonts() + pretendard()

    header = (
        "/* Self-hosted webfonts. Schibsted Grotesk and IBM Plex Mono are\n"
        "   latin subsets under the SIL Open Font License 1.1; Pretendard is\n"
        "   subset to the Korean the site actually sets (also OFL 1.1).\n"
        "   Regenerated by scripts/fetch-fonts.py — do not edit by hand. */\n\n"
    )
    pathlib.Path("src/fonts.css").write_text(header + "\n\n".join(rules) + "\n")

    for f in sorted(OUT.iterdir()):
        print(f"  {f.stat().st_size / 1024:6.1f} KB  {f.name}")
    total = sum(f.stat().st_size for f in OUT.iterdir()) / 1024
    print(f"  {total:6.1f} KB  total")


if __name__ == "__main__":
    main()
