/**
 * Manifest for the hero's morph geometry. Generated by
 * scripts/build-hero-geometry.mjs — do not edit by hand; re-run the script.
 *
 * Source: Pretendard Bold (SIL Open Font License 1.1), pinned as a
 * devDependency. Outlines are flattened, contour-matched between each jamo and
 * its Latin target, and extruded; the arrays live in hero-geometry.bin and
 * every offset below is a byte offset into it.
 *
 * All coordinates are in cap heights, centred on each glyph's visual centroid.
 */

export interface MeshEntry {
  name: string;
  /** "morph" glyphs interpolate to a Latin letter; "arrive" ones do not. */
  kind: "morph" | "arrive";
  /** Source jamo, for morph meshes. */
  jamo: string | null;
  /** The Latin letter this mesh is, or becomes. */
  latin: string;
  /** Index into the nine jamo of 박상현. */
  jamoIndex: number | null;
  /** Which piece of a one-to-many split this is, and how many there are. */
  splitIndex: number | null;
  splitCount: number | null;
  /** 박 = 0, 상 = 1, 현 = 2. */
  syllable: number | null;
  role: "initial" | "vowel" | "final" | null;
  /** Position in "SEAN", for arriving meshes. */
  arriveIndex: number | null;
  contours: number;
  /** [minX, minY, maxX, maxY] of the ink, in cap heights, in each state. */
  sourceBounds: [number, number, number, number];
  targetBounds: [number, number, number, number];
  /** Advance widths in cap heights, for typesetting each state. */
  sourceAdvance: number | null;
  targetAdvance: number;
  /**
   * Pen origin relative to the recentred geometry, in cap heights. Placing a
   * glyph at pen position X with its baseline on y = 0 means positioning the
   * mesh at (origin[0] + X, origin[1]).
   */
  sourceOrigin: [number, number];
  targetOrigin: [number, number];
  vertexCount: number;
  indexCount: number;
  /** Byte offsets into the blob. */
  position: number;
  aTarget: number;
  normal: number;
  aTargetNormal: number;
  aSeed: number;
  index: number;
}

/** Points per contour. Every contour in the file has exactly this many. */
export const POINTS_PER_CONTOUR = 192;

/** aSeed is a normalised byte; index buffers are Uint16. */
export const SEED_BYTES = 1;

/** Extrusion depth, in cap heights. */
export const DEPTH = 0.17;

export const BLOB = "hero-geometry.bin";

export const MESHES: MeshEntry[] = [
  {
    "name": "ㅂ-P-0-0",
    "kind": "morph",
    "jamo": "ㅂ",
    "latin": "P",
    "jamoIndex": 0,
    "splitIndex": 0,
    "splitCount": 1,
    "syllable": 0,
    "role": "initial",
    "arriveIndex": null,
    "contours": 2,
    "sourceBounds": [
      -0.3824,
      -0.3793,
      0.3852,
      0.2818
    ],
    "targetBounds": [
      -0.5139,
      -0.6372,
      0.2015,
      0.3306
    ],
    "sourceAdvance": 1.2224,
    "targetAdvance": 0.8812,
    "sourceOrigin": [
      0.613950276243094,
      0.5644567219152855
    ],
    "targetOrigin": [
      0.6146207306731394,
      0.6526347034195239
    ],
    "vertexCount": 2304,
    "position": 0,
    "aTarget": 13824,
    "normal": 27648,
    "aTargetNormal": 41472,
    "aSeed": 55296,
    "index": 57600,
    "indexCount": 5640
  },
  {
    "name": "ㅏ-A-1-0",
    "kind": "morph",
    "jamo": "ㅏ",
    "latin": "A",
    "jamoIndex": 1,
    "splitIndex": 0,
    "splitCount": 1,
    "syllable": 0,
    "role": "vowel",
    "arriveIndex": null,
    "contours": 2,
    "sourceBounds": [
      -0.1797,
      -0.6385,
      0.2241,
      0.5687
    ],
    "targetBounds": [
      -0.4627,
      -0.3845,
      0.4608,
      0.5824
    ],
    "sourceAdvance": 1.2224,
    "targetAdvance": 1.0152,
    "sourceOrigin": [
      0.681975138121547,
      0.5314226519337016
    ],
    "targetOrigin": [
      0.5077117863720073,
      0.3996316758747698
    ],
    "vertexCount": 2304,
    "position": 68880,
    "aTarget": 82704,
    "normal": 96528,
    "aTargetNormal": 110352,
    "aSeed": 124176,
    "index": 126480,
    "indexCount": 6318
  },
  {
    "name": "ㄱ-R-2-0",
    "kind": "morph",
    "jamo": "ㄱ",
    "latin": "R",
    "jamoIndex": 2,
    "splitIndex": 0,
    "splitCount": 2,
    "syllable": 0,
    "role": "final",
    "arriveIndex": null,
    "contours": 2,
    "sourceBounds": [
      -0.462,
      -0.3882,
      0.3106,
      0.2578
    ],
    "targetBounds": [
      -0.53,
      -0.6572,
      0.2138,
      0.3166
    ],
    "sourceAdvance": 1.2224,
    "targetAdvance": 0.8936,
    "sourceOrigin": [
      0.68646408839779,
      0.572744014732965
    ],
    "targetOrigin": [
      0.6322060083405623,
      0.665378199441485
    ],
    "vertexCount": 2304,
    "position": 139116,
    "aTarget": 152940,
    "normal": 166764,
    "aTargetNormal": 180588,
    "aSeed": 194412,
    "index": 196716,
    "indexCount": 5736
  },
  {
    "name": "ㄱ-K-2-1",
    "kind": "morph",
    "jamo": "ㄱ",
    "latin": "K",
    "jamoIndex": 2,
    "splitIndex": 1,
    "splitCount": 2,
    "syllable": 0,
    "role": "final",
    "arriveIndex": null,
    "contours": 1,
    "sourceBounds": [
      -0.462,
      -0.3882,
      0.3106,
      0.2578
    ],
    "targetBounds": [
      -0.3412,
      -0.4746,
      0.4561,
      0.5021
    ],
    "sourceAdvance": 1.2224,
    "targetAdvance": 0.9378,
    "sourceOrigin": [
      0.68646408839779,
      0.572744014732965
    ],
    "targetOrigin": [
      0.4434764130896728,
      0.4895877603059923
    ],
    "vertexCount": 1152,
    "position": 208188,
    "aTarget": 215100,
    "normal": 222012,
    "aTargetNormal": 228924,
    "aSeed": 235836,
    "index": 236988,
    "indexCount": 3444
  },
  {
    "name": "ㅅ-S-3-0",
    "kind": "morph",
    "jamo": "ㅅ",
    "latin": "S",
    "jamoIndex": 3,
    "splitIndex": 0,
    "splitCount": 1,
    "syllable": 1,
    "role": "initial",
    "arriveIndex": null,
    "contours": 1,
    "sourceBounds": [
      -0.4434,
      -0.1943,
      0.4422,
      0.4877
    ],
    "targetBounds": [
      -0.3821,
      -0.4942,
      0.3691,
      0.4974
    ],
    "sourceAdvance": 1.2224,
    "targetAdvance": 0.8909,
    "sourceOrigin": [
      0.6138674390136252,
      0.3628075119168778
    ],
    "targetOrigin": [
      0.45233369767457143,
      0.4984353185785335
    ],
    "vertexCount": 1152,
    "position": 243876,
    "aTarget": 250788,
    "normal": 257700,
    "aTargetNormal": 264612,
    "aSeed": 271524,
    "index": 272676,
    "indexCount": 3444
  },
  {
    "name": "ㅏ-A-4-0",
    "kind": "morph",
    "jamo": "ㅏ",
    "latin": "A",
    "jamoIndex": 4,
    "splitIndex": 0,
    "splitCount": 1,
    "syllable": 1,
    "role": "vowel",
    "arriveIndex": null,
    "contours": 2,
    "sourceBounds": [
      -0.1797,
      -0.6385,
      0.2241,
      0.5687
    ],
    "targetBounds": [
      -0.4627,
      -0.3845,
      0.4608,
      0.5824
    ],
    "sourceAdvance": 1.2224,
    "targetAdvance": 1.0152,
    "sourceOrigin": [
      0.681975138121547,
      0.5314226519337016
    ],
    "targetOrigin": [
      0.5077117863720073,
      0.3996316758747698
    ],
    "vertexCount": 2304,
    "position": 279564,
    "aTarget": 293388,
    "normal": 307212,
    "aTargetNormal": 321036,
    "aSeed": 334860,
    "index": 337164,
    "indexCount": 6318
  },
  {
    "name": "ㅇ-N-5-0",
    "kind": "morph",
    "jamo": "ㅇ",
    "latin": "N",
    "jamoIndex": 5,
    "splitIndex": 0,
    "splitCount": 2,
    "syllable": 1,
    "role": "final",
    "arriveIndex": null,
    "contours": 2,
    "sourceBounds": [
      -0.3842,
      -0.3357,
      0.3864,
      0.3382
    ],
    "targetBounds": [
      -0.3996,
      -0.482,
      0.3987,
      0.482
    ],
    "sourceAdvance": 1.2224,
    "targetAdvance": 1.0028,
    "sourceOrigin": [
      0.6121373466365245,
      0.5112222070852037
    ],
    "targetOrigin": [
      0.501841620626151,
      0.5
    ],
    "vertexCount": 2304,
    "position": 349800,
    "aTarget": 363624,
    "normal": 377448,
    "aTargetNormal": 391272,
    "aSeed": 405096,
    "index": 407400,
    "indexCount": 6912
  },
  {
    "name": "ㅇ-G-5-1",
    "kind": "morph",
    "jamo": "ㅇ",
    "latin": "G",
    "jamoIndex": 5,
    "splitIndex": 1,
    "splitCount": 2,
    "syllable": 1,
    "role": "final",
    "arriveIndex": null,
    "contours": 2,
    "sourceBounds": [
      -0.3842,
      -0.3357,
      0.3864,
      0.3382
    ],
    "targetBounds": [
      -0.4413,
      -0.5017,
      0.426,
      0.4898
    ],
    "sourceAdvance": 1.2224,
    "targetAdvance": 1.0359,
    "sourceOrigin": [
      0.6121373466365245,
      0.5112222070852037
    ],
    "targetOrigin": [
      0.5242403356260981,
      0.5060064971039457
    ],
    "vertexCount": 2304,
    "position": 421224,
    "aTarget": 435048,
    "normal": 448872,
    "aTargetNormal": 462696,
    "aSeed": 476520,
    "index": 478824,
    "indexCount": 6912
  },
  {
    "name": "ㅎ-H-6-0",
    "kind": "morph",
    "jamo": "ㅎ",
    "latin": "H",
    "jamoIndex": 6,
    "splitIndex": 0,
    "splitCount": 1,
    "syllable": 2,
    "role": "initial",
    "arriveIndex": null,
    "contours": 3,
    "sourceBounds": [
      -0.4064,
      -0.2435,
      0.4061,
      0.5816
    ],
    "targetBounds": [
      -0.4063,
      -0.482,
      0.4072,
      0.482
    ],
    "sourceAdvance": 1.2224,
    "targetAdvance": 1.018,
    "sourceOrigin": [
      0.6157086340249072,
      0.3623293139605465
    ],
    "targetOrigin": [
      0.5085174953959485,
      0.5
    ],
    "vertexCount": 3456,
    "position": 492648,
    "aTarget": 513384,
    "normal": 534120,
    "aTargetNormal": 554856,
    "aSeed": 575592,
    "index": 579048,
    "indexCount": 10356
  },
  {
    "name": "ㅕ-Y-7-0",
    "kind": "morph",
    "jamo": "ㅕ",
    "latin": "Y",
    "jamoIndex": 7,
    "splitIndex": 0,
    "splitCount": 3,
    "syllable": 2,
    "role": "vowel",
    "arriveIndex": null,
    "contours": 1,
    "sourceBounds": [
      -0.1946,
      -0.6496,
      0.2201,
      0.5577
    ],
    "targetBounds": [
      -0.4483,
      -0.5676,
      0.4461,
      0.4071
    ],
    "sourceAdvance": 1.2224,
    "targetAdvance": 0.9834,
    "sourceOrigin": [
      0.5909300184162062,
      0.5432780847145487
    ],
    "targetOrigin": [
      0.49185082872928176,
      0.5850828729281768
    ],
    "vertexCount": 1152,
    "position": 599760,
    "aTarget": 606672,
    "normal": 613584,
    "aTargetNormal": 620496,
    "aSeed": 627408,
    "index": 628560,
    "indexCount": 3444
  },
  {
    "name": "ㅕ-E-7-1",
    "kind": "morph",
    "jamo": "ㅕ",
    "latin": "E",
    "jamoIndex": 7,
    "splitIndex": 1,
    "splitCount": 3,
    "syllable": 2,
    "role": "vowel",
    "arriveIndex": null,
    "contours": 1,
    "sourceBounds": [
      -0.1946,
      -0.6496,
      0.2201,
      0.5577
    ],
    "targetBounds": [
      -0.3812,
      -0.482,
      0.2555,
      0.482
    ],
    "sourceAdvance": 1.2224,
    "targetAdvance": 0.8329,
    "sourceOrigin": [
      0.5909300184162062,
      0.5432780847145487
    ],
    "targetOrigin": [
      0.48342541436464087,
      0.5
    ],
    "vertexCount": 1152,
    "position": 635448,
    "aTarget": 642360,
    "normal": 649272,
    "aTargetNormal": 656184,
    "aSeed": 663096,
    "index": 664248,
    "indexCount": 3444
  },
  {
    "name": "ㅕ-O-7-2",
    "kind": "morph",
    "jamo": "ㅕ",
    "latin": "O",
    "jamoIndex": 7,
    "splitIndex": 2,
    "splitCount": 3,
    "syllable": 2,
    "role": "vowel",
    "arriveIndex": null,
    "contours": 2,
    "sourceBounds": [
      -0.1946,
      -0.6496,
      0.2201,
      0.5577
    ],
    "targetBounds": [
      -0.4497,
      -0.4958,
      0.4494,
      0.4958
    ],
    "sourceAdvance": 1.2224,
    "targetAdvance": 1.0649,
    "sourceOrigin": [
      0.5909300184162062,
      0.5432780847145487
    ],
    "targetOrigin": [
      0.5326313840750172,
      0.5000431208320744
    ],
    "vertexCount": 2304,
    "position": 671136,
    "aTarget": 684960,
    "normal": 698784,
    "aTargetNormal": 712608,
    "aSeed": 726432,
    "index": 728736,
    "indexCount": 6912
  },
  {
    "name": "ㄴ-N-8-0",
    "kind": "morph",
    "jamo": "ㄴ",
    "latin": "N",
    "jamoIndex": 8,
    "splitIndex": 0,
    "splitCount": 1,
    "syllable": 2,
    "role": "final",
    "arriveIndex": null,
    "contours": 1,
    "sourceBounds": [
      -0.3152,
      -0.2511,
      0.4699,
      0.3751
    ],
    "targetBounds": [
      -0.3996,
      -0.482,
      0.3987,
      0.482
    ],
    "sourceAdvance": 1.2224,
    "targetAdvance": 1.0028,
    "sourceOrigin": [
      0.5418968692449355,
      0.45488029465930013
    ],
    "targetOrigin": [
      0.501841620626151,
      0.5
    ],
    "vertexCount": 1152,
    "position": 742560,
    "aTarget": 749472,
    "normal": 756384,
    "aTargetNormal": 763296,
    "aSeed": 770208,
    "index": 771360,
    "indexCount": 3444
  },
  {
    "name": "arrive-S-0",
    "kind": "arrive",
    "jamo": null,
    "latin": "S",
    "jamoIndex": null,
    "splitIndex": null,
    "splitCount": null,
    "syllable": null,
    "role": null,
    "arriveIndex": 0,
    "contours": 1,
    "sourceBounds": [
      -0.3821,
      -0.4942,
      0.3691,
      0.4974
    ],
    "targetBounds": [
      -0.3821,
      -0.4942,
      0.3691,
      0.4974
    ],
    "sourceAdvance": null,
    "targetAdvance": 0.8909,
    "sourceOrigin": [
      0.45233369767457143,
      0.4984353185785335
    ],
    "targetOrigin": [
      0.45233369767457143,
      0.4984353185785335
    ],
    "vertexCount": 1152,
    "position": 778248,
    "aTarget": 785160,
    "normal": 792072,
    "aTargetNormal": 798984,
    "aSeed": 805896,
    "index": 807048,
    "indexCount": 3444
  },
  {
    "name": "arrive-E-1",
    "kind": "arrive",
    "jamo": null,
    "latin": "E",
    "jamoIndex": null,
    "splitIndex": null,
    "splitCount": null,
    "syllable": null,
    "role": null,
    "arriveIndex": 1,
    "contours": 1,
    "sourceBounds": [
      -0.3812,
      -0.482,
      0.2555,
      0.482
    ],
    "targetBounds": [
      -0.3812,
      -0.482,
      0.2555,
      0.482
    ],
    "sourceAdvance": null,
    "targetAdvance": 0.8329,
    "sourceOrigin": [
      0.48342541436464087,
      0.5
    ],
    "targetOrigin": [
      0.48342541436464087,
      0.5
    ],
    "vertexCount": 1152,
    "position": 813936,
    "aTarget": 820848,
    "normal": 827760,
    "aTargetNormal": 834672,
    "aSeed": 841584,
    "index": 842736,
    "indexCount": 3444
  },
  {
    "name": "arrive-A-2",
    "kind": "arrive",
    "jamo": null,
    "latin": "A",
    "jamoIndex": null,
    "splitIndex": null,
    "splitCount": null,
    "syllable": null,
    "role": null,
    "arriveIndex": 2,
    "contours": 2,
    "sourceBounds": [
      -0.4627,
      -0.3845,
      0.4608,
      0.5824
    ],
    "targetBounds": [
      -0.4627,
      -0.3845,
      0.4608,
      0.5824
    ],
    "sourceAdvance": null,
    "targetAdvance": 1.0152,
    "sourceOrigin": [
      0.5077117863720073,
      0.3996316758747698
    ],
    "targetOrigin": [
      0.5077117863720073,
      0.3996316758747698
    ],
    "vertexCount": 2304,
    "position": 849624,
    "aTarget": 863448,
    "normal": 877272,
    "aTargetNormal": 891096,
    "aSeed": 904920,
    "index": 907224,
    "indexCount": 6318
  },
  {
    "name": "arrive-N-3",
    "kind": "arrive",
    "jamo": null,
    "latin": "N",
    "jamoIndex": null,
    "splitIndex": null,
    "splitCount": null,
    "syllable": null,
    "role": null,
    "arriveIndex": 3,
    "contours": 1,
    "sourceBounds": [
      -0.3996,
      -0.482,
      0.3987,
      0.482
    ],
    "targetBounds": [
      -0.3996,
      -0.482,
      0.3987,
      0.482
    ],
    "sourceAdvance": null,
    "targetAdvance": 1.0028,
    "sourceOrigin": [
      0.501841620626151,
      0.5
    ],
    "targetOrigin": [
      0.501841620626151,
      0.5
    ],
    "vertexCount": 1152,
    "position": 919860,
    "aTarget": 926772,
    "normal": 933684,
    "aTargetNormal": 940596,
    "aSeed": 947508,
    "index": 948660,
    "indexCount": 3444
  }
];
