/**
 * Manifest for the hero's morph geometry. Generated by
 * scripts/build-hero-geometry.mjs — do not edit by hand; re-run the script.
 *
 * Source: Pretendard Bold (SIL Open Font License 1.1), pinned as a
 * devDependency. Outlines are flattened, contour-matched between each jamo and
 * its Latin target, and extruded; the arrays live in hero-geometry.bin and
 * every offset below is a byte offset into it.
 *
 * All coordinates are in cap heights, centred on each glyph's visual centroid.
 */

export interface MeshEntry {
  name: string;
  /** "morph" glyphs interpolate to a Latin letter; "arrive" ones do not. */
  kind: "morph" | "arrive";
  /** Source jamo, for morph meshes. */
  jamo: string | null;
  /** The Latin letter this mesh is, or becomes. */
  latin: string;
  /** Index into the nine jamo of 박상현. */
  jamoIndex: number | null;
  /** Which piece of a one-to-many split this is, and how many there are. */
  splitIndex: number | null;
  splitCount: number | null;
  /** 박 = 0, 상 = 1, 현 = 2. */
  syllable: number | null;
  role: "initial" | "vowel" | "final" | null;
  /** Position in "SEAN", for arriving meshes. */
  arriveIndex: number | null;
  contours: number;
  vertexCount: number;
  indexCount: number;
  /** Byte offsets into the blob. */
  position: number;
  aTarget: number;
  normal: number;
  aTargetNormal: number;
  aSeed: number;
  index: number;
}

/** Points per contour. Every contour in the file has exactly this many. */
export const POINTS_PER_CONTOUR = 256;

/** Extrusion depth, in cap heights. */
export const DEPTH = 0.17;

export const BLOB = "hero-geometry.bin";

export const MESHES: MeshEntry[] = [
  {
    "name": "ㅂ-P-0-0",
    "kind": "morph",
    "jamo": "ㅂ",
    "latin": "P",
    "jamoIndex": 0,
    "splitIndex": 0,
    "splitCount": 1,
    "syllable": 0,
    "role": "initial",
    "arriveIndex": null,
    "contours": 2,
    "vertexCount": 3072,
    "position": 0,
    "aTarget": 36864,
    "normal": 73728,
    "aTargetNormal": 110592,
    "aSeed": 147456,
    "index": 159744,
    "indexCount": 7482
  },
  {
    "name": "ㅏ-A-1-0",
    "kind": "morph",
    "jamo": "ㅏ",
    "latin": "A",
    "jamoIndex": 1,
    "splitIndex": 0,
    "splitCount": 1,
    "syllable": 0,
    "role": "vowel",
    "arriveIndex": null,
    "contours": 2,
    "vertexCount": 3072,
    "position": 189672,
    "aTarget": 226536,
    "normal": 263400,
    "aTargetNormal": 300264,
    "aSeed": 337128,
    "index": 349416,
    "indexCount": 8304
  },
  {
    "name": "ㄱ-R-2-0",
    "kind": "morph",
    "jamo": "ㄱ",
    "latin": "R",
    "jamoIndex": 2,
    "splitIndex": 0,
    "splitCount": 2,
    "syllable": 0,
    "role": "final",
    "arriveIndex": null,
    "contours": 2,
    "vertexCount": 3072,
    "position": 382632,
    "aTarget": 419496,
    "normal": 456360,
    "aTargetNormal": 493224,
    "aSeed": 530088,
    "index": 542376,
    "indexCount": 7602
  },
  {
    "name": "ㄱ-K-2-1",
    "kind": "morph",
    "jamo": "ㄱ",
    "latin": "K",
    "jamoIndex": 2,
    "splitIndex": 1,
    "splitCount": 2,
    "syllable": 0,
    "role": "final",
    "arriveIndex": null,
    "contours": 1,
    "vertexCount": 1536,
    "position": 572784,
    "aTarget": 591216,
    "normal": 609648,
    "aTargetNormal": 628080,
    "aSeed": 646512,
    "index": 652656,
    "indexCount": 4596
  },
  {
    "name": "ㅅ-S-3-0",
    "kind": "morph",
    "jamo": "ㅅ",
    "latin": "S",
    "jamoIndex": 3,
    "splitIndex": 0,
    "splitCount": 1,
    "syllable": 1,
    "role": "initial",
    "arriveIndex": null,
    "contours": 1,
    "vertexCount": 1536,
    "position": 671040,
    "aTarget": 689472,
    "normal": 707904,
    "aTargetNormal": 726336,
    "aSeed": 744768,
    "index": 750912,
    "indexCount": 4596
  },
  {
    "name": "ㅏ-A-4-0",
    "kind": "morph",
    "jamo": "ㅏ",
    "latin": "A",
    "jamoIndex": 4,
    "splitIndex": 0,
    "splitCount": 1,
    "syllable": 1,
    "role": "vowel",
    "arriveIndex": null,
    "contours": 2,
    "vertexCount": 3072,
    "position": 769296,
    "aTarget": 806160,
    "normal": 843024,
    "aTargetNormal": 879888,
    "aSeed": 916752,
    "index": 929040,
    "indexCount": 8304
  },
  {
    "name": "ㅇ-N-5-0",
    "kind": "morph",
    "jamo": "ㅇ",
    "latin": "N",
    "jamoIndex": 5,
    "splitIndex": 0,
    "splitCount": 2,
    "syllable": 1,
    "role": "final",
    "arriveIndex": null,
    "contours": 2,
    "vertexCount": 3072,
    "position": 962256,
    "aTarget": 999120,
    "normal": 1035984,
    "aTargetNormal": 1072848,
    "aSeed": 1109712,
    "index": 1122000,
    "indexCount": 9210
  },
  {
    "name": "ㅇ-G-5-1",
    "kind": "morph",
    "jamo": "ㅇ",
    "latin": "G",
    "jamoIndex": 5,
    "splitIndex": 1,
    "splitCount": 2,
    "syllable": 1,
    "role": "final",
    "arriveIndex": null,
    "contours": 2,
    "vertexCount": 3072,
    "position": 1158840,
    "aTarget": 1195704,
    "normal": 1232568,
    "aTargetNormal": 1269432,
    "aSeed": 1306296,
    "index": 1318584,
    "indexCount": 9210
  },
  {
    "name": "ㅎ-H-6-0",
    "kind": "morph",
    "jamo": "ㅎ",
    "latin": "H",
    "jamoIndex": 6,
    "splitIndex": 0,
    "splitCount": 1,
    "syllable": 2,
    "role": "initial",
    "arriveIndex": null,
    "contours": 3,
    "vertexCount": 4608,
    "position": 1355424,
    "aTarget": 1410720,
    "normal": 1466016,
    "aTargetNormal": 1521312,
    "aSeed": 1576608,
    "index": 1595040,
    "indexCount": 13794
  },
  {
    "name": "ㅕ-Y-7-0",
    "kind": "morph",
    "jamo": "ㅕ",
    "latin": "Y",
    "jamoIndex": 7,
    "splitIndex": 0,
    "splitCount": 3,
    "syllable": 2,
    "role": "vowel",
    "arriveIndex": null,
    "contours": 1,
    "vertexCount": 1536,
    "position": 1650216,
    "aTarget": 1668648,
    "normal": 1687080,
    "aTargetNormal": 1705512,
    "aSeed": 1723944,
    "index": 1730088,
    "indexCount": 4596
  },
  {
    "name": "ㅕ-E-7-1",
    "kind": "morph",
    "jamo": "ㅕ",
    "latin": "E",
    "jamoIndex": 7,
    "splitIndex": 1,
    "splitCount": 3,
    "syllable": 2,
    "role": "vowel",
    "arriveIndex": null,
    "contours": 1,
    "vertexCount": 1536,
    "position": 1748472,
    "aTarget": 1766904,
    "normal": 1785336,
    "aTargetNormal": 1803768,
    "aSeed": 1822200,
    "index": 1828344,
    "indexCount": 4596
  },
  {
    "name": "ㅕ-O-7-2",
    "kind": "morph",
    "jamo": "ㅕ",
    "latin": "O",
    "jamoIndex": 7,
    "splitIndex": 2,
    "splitCount": 3,
    "syllable": 2,
    "role": "vowel",
    "arriveIndex": null,
    "contours": 2,
    "vertexCount": 3072,
    "position": 1846728,
    "aTarget": 1883592,
    "normal": 1920456,
    "aTargetNormal": 1957320,
    "aSeed": 1994184,
    "index": 2006472,
    "indexCount": 9216
  },
  {
    "name": "ㄴ-N-8-0",
    "kind": "morph",
    "jamo": "ㄴ",
    "latin": "N",
    "jamoIndex": 8,
    "splitIndex": 0,
    "splitCount": 1,
    "syllable": 2,
    "role": "final",
    "arriveIndex": null,
    "contours": 1,
    "vertexCount": 1536,
    "position": 2043336,
    "aTarget": 2061768,
    "normal": 2080200,
    "aTargetNormal": 2098632,
    "aSeed": 2117064,
    "index": 2123208,
    "indexCount": 4596
  },
  {
    "name": "arrive-S-0",
    "kind": "arrive",
    "jamo": null,
    "latin": "S",
    "jamoIndex": null,
    "splitIndex": null,
    "splitCount": null,
    "syllable": null,
    "role": null,
    "arriveIndex": 0,
    "contours": 1,
    "vertexCount": 1536,
    "position": 2141592,
    "aTarget": 2160024,
    "normal": 2178456,
    "aTargetNormal": 2196888,
    "aSeed": 2215320,
    "index": 2221464,
    "indexCount": 4596
  },
  {
    "name": "arrive-E-1",
    "kind": "arrive",
    "jamo": null,
    "latin": "E",
    "jamoIndex": null,
    "splitIndex": null,
    "splitCount": null,
    "syllable": null,
    "role": null,
    "arriveIndex": 1,
    "contours": 1,
    "vertexCount": 1536,
    "position": 2239848,
    "aTarget": 2258280,
    "normal": 2276712,
    "aTargetNormal": 2295144,
    "aSeed": 2313576,
    "index": 2319720,
    "indexCount": 4596
  },
  {
    "name": "arrive-A-2",
    "kind": "arrive",
    "jamo": null,
    "latin": "A",
    "jamoIndex": null,
    "splitIndex": null,
    "splitCount": null,
    "syllable": null,
    "role": null,
    "arriveIndex": 2,
    "contours": 2,
    "vertexCount": 3072,
    "position": 2338104,
    "aTarget": 2374968,
    "normal": 2411832,
    "aTargetNormal": 2448696,
    "aSeed": 2485560,
    "index": 2497848,
    "indexCount": 8304
  },
  {
    "name": "arrive-N-3",
    "kind": "arrive",
    "jamo": null,
    "latin": "N",
    "jamoIndex": null,
    "splitIndex": null,
    "splitCount": null,
    "syllable": null,
    "role": null,
    "arriveIndex": 3,
    "contours": 1,
    "vertexCount": 1536,
    "position": 2531064,
    "aTarget": 2549496,
    "normal": 2567928,
    "aTargetNormal": 2586360,
    "aSeed": 2604792,
    "index": 2610936,
    "indexCount": 4596
  }
];
